Add mac vendor check
REZAL-AM-KIN/niki-s pull request #12
Opened 2022-08-20 18:10 UTC by OSiG43

2022-08-21 07:31 UTC, lenwe171175 requested changes
Hello, bonne idée d'ajouter le type de vendeur. 
Mais je ne comprends pourquoi tu le fais ici, à chaque fois que tu vas aller sur la page d'approbation, tu vas devoir interroger l'api macvendors. Pourquoi plutôt ne pas compléter device.vendor au moment où l'utilisateur l'enregistre, une bonne fois pour toute ?

2022-08-21 08:35 UTC, tag166tt requested changes

2022-08-21 08:35 UTC, tag166tt commented on appmacgest/views.py
> +
Des packages python (genre [mac-vendor-lookup](https://pypi.org/project/mac-vendor-lookup/) existent pour pas avoir à taper dans une API externe qui a du rate limiting à 1k rq/jour et 1rq/s et qui du coup pourrait foutre niki en vrac.
Après, y a pas d'auth donc y a moyen de contourner cette limitation, mais pas fou d'un point de vue respect d'une API publique.

2022-08-21 09:32 UTC, OSiG43 commented on appmacgest/views.py
> +
je le fais ici car je me suis dit que ce n'était pas une info très intéressante à stocker.
Sinon pour le fait de taper sur une api externe, j'étais moyen chaud aussi mais j'avais pas vraiment d'autre solution. Je vais regarder le package python du coup.

2022-08-23 07:41 UTC, lenwe171175 submitted a review, later dismissed
Donc on le laisse sur cette page plutôt que de le stocker ? Pourquoi pas...

2022-08-23 09:31 UTC, OSiG43 commented
ça me semble plus logique, car finalement c'est stocké des infos pour rien, m'enfin si tu penses que c'est mieux, je le stocke

2022-08-23 11:06 UTC, tag166tt requested changes

2022-08-23 11:06 UTC, tag166tt commented on appmacgest/views.py
> +        device.vendor = MacLookup().lookup(device.mac)
J'aurais tendance à instancier la lib dans les settings pour qu'au démarrage on puisse faire l'update comme expliqué [ici](https://github.com/bauerj/mac_vendor_lookup#update-the-vendor-list).
Et si besoin spécifier le cache de façon explicite (même pas si pas forcément utile) comme [ici](https://github.com/bauerj/mac_vendor_lookup#vendor-list-custom-location-or-path).

2022-08-23 11:07 UTC, tag166tt commented on appmacgest/views.py
> +        device.vendor = MacLookup().lookup(device.mac)
Et sinon, ok pour la détermination du fabriquant ici, ça n'a aucun intérêt à part prendre de la place dans la DB.

2022-08-23 17:16 UTC, OSiG43 commented on appmacgest/views.py
> +        device.vendor = MacLookup().lookup(device.mac)
ça marche, à vrai dire j'ai eu la flemme de le faire mais c'est vrai que c'est beaucoup mieux.

2024-08-06 15:10 UTC, OSiG43 commented on appmacgest/views.py
> +            device.vendor = "Inconnu"
Comme suggeré par @lenwe171175, ça semble mieux de déplacer la recherche du vendor lors de la création et le stocker dans la db pour eviter un chargement long en cas de nombreuse mac en attente de validation.

@peufgeul  tu en penses quoi ?

2024-08-06 15:20 UTC, peufgeul commented on appmacgest/views.py
> +            device.vendor = "Inconnu"
Si je dis pas de bétise, avec la config actuelle, l'identification des adresses MAC avec MACLOOKUP.lookup() se fait avec un cache local.
Il est dans un fichier (./.cache/mac-vendors.txt) qui est mis à jour par l'appel de MACLOOKUP.update_vendors().
Et y'a une tâche pour ça qui tourne à 00:32

2024-08-06 15:25 UTC, OSiG43 commented on appmacgest/views.py
> +            device.vendor = "Inconnu"
Yep, j'ai vu, mais ça reste un peu chelou de faire des taches "longues" pendant une requete.

Bon après c'est pas dramatique, si tu trouves ça ok, je valide la pr.

2024-08-06 15:34 UTC, peufgeul commented on appmacgest/views.py
> +            device.vendor = "Inconnu"
bah après si les vendeurs sont chargés, c'est juste formater l'adresse MAC et récupérer la valeur dans un dictionnaire dont la clé est le début de l'adresse MAC

2024-08-06 15:35 UTC, OSiG43 commented on appmacgest/views.py
> +            device.vendor = "Inconnu"
Convaincu

2024-08-06 15:36 UTC, peufgeul approved these changes
lgtm

2024-08-18 16:32 UTC, peufgeul commented on appmacgest/views.py
> +            device.vendor = "Inconnu"
j'ai testé avec 100 appareils (bon j'ai juste les 2 adresses mac de mon pc pour en avoir des "vrais"), ça n'ajoute pas de temps mesurable à la requête entre cette branche avec maclookup et une autre branche

2024-08-18 16:34 UTC, merged