Auto account deactivation
REZAL-AM-KIN/niki-s pull request #34
Opened 2022-09-10 15:20 UTC by OSiG43

2022-09-10 19:54 UTC, lenwe171175 submitted a review, later dismissed

2022-09-10 19:54 UTC, lenwe171175 commented on templates/appuser/cotiz_expired_email.txt
> +Si vous souhaitez renouveller votre cotisation, veuillez contacter l'équipe rezal : contact@rezal.fr
renouveler

2022-09-10 19:54 UTC, lenwe171175 commented on niki/settings.py
> +        "schedule": crontab(),
cette tâche n'est pas planifiée du coup ?

2022-09-11 09:53 UTC, tag166tt requested changes

2022-09-11 09:53 UTC, tag166tt commented on niki/settings.py
>  CASHIER_PHONE = getenv("LYDIA_CASHIER_PHONE", "")
Pourquoi les variables sont doublées?

2022-09-11 09:53 UTC, tag166tt commented on niki/settings.py
> +        "schedule": crontab(),
Vraiment besoin de run ça toutes les minutes?

2022-09-11 09:53 UTC, tag166tt commented on appuser/tasks.py
> +from django.template import Context
Import non utilisé

2022-09-11 09:53 UTC, tag166tt commented on niki/celery.py
> +
Peut-être pas utile à garder?

2022-09-11 09:53 UTC, tag166tt commented on templates/appuser/cotiz_expired_email.txt
> +Votre cotisation au rezal a d'expirée, vous n'avez donc plus accès à internet.
`a d'expirée` ? 🤔

2022-10-02 12:36 UTC, tag166tt approved these changes
LGTM

2022-10-02 12:49 UTC, merged