Separate entity model
REZAL-AM-KIN/niki-s pull request #43
Opened 2023-03-07 23:06 UTC by OSiG43

Séparation des entités des groupes. En effet comme les groupes servent à gérer les permissions il peut y avoir des groupes différents qui ont accès à la même entité. Par ex : vp_cvis et team_cvis sont 2 groupes accédants tous deux à l'entité cvis

2023-04-04 18:27 UTC, Teiwin requested changes
seems good, juste quelques interrogations

2023-04-04 18:27 UTC, Teiwin commented on appuser/models.py
ok, semble bon pour moi, pas de description pour les groupes ?
jsp, je nom est peut-être assez explicite

2023-04-04 18:27 UTC, Teiwin commented on appkfet/models.py
> +
pourquoi y a des des newlines qui pop? :rofl:

2023-04-04 18:27 UTC, Teiwin commented on appkfet/models.py
semble ok aussi.
J'aurais bien aimé que le [color selector](https://github.com/REZAL-AM-KIN/niki-s/blob/cb87b796df98a2e53a416b955f0354b78e4039f3/appuser/forms.py#L100) soit encore là.
(d'ailleurs il ne sert plus à rien dans les Groups)

2023-04-07 19:11 UTC, OSiG43 commented on appuser/models.py
> +        from appkfet.models import Entity
c'est pour éviter les imports circulaire

2023-04-07 19:11 UTC, OSiG43 commented on appuser/models.py
> +    from appkfet.models import Entity
c'est pour éviter les imports circulaire

2023-04-07 19:13 UTC, OSiG43 commented on appuser/models.py
Je trouve que la description peut être utile, je la met en option de toute façon

2023-04-07 19:48 UTC, Teiwin approved these changes
lgtm

2023-04-07 19:49 UTC, merged