Gestion des produits kfet
REZAL-AM-KIN/niki-s pull request #49
Opened 2023-08-04 08:13 UTC by peufgeul

Modification de la bdd et de l'api pour permettre la gestion des produits en fonction de leur entité, et création d'un moyen de permission associé

- ajout d'une relation ManyToMany entre groupes (appuser) et entitys (appkfet) nommé entities_manageable (groups_management pour entitys)
En plus de la permission appkfet|produit|Add/change/delete, l'utilisateur doit être dans un groupe qui contient la ou les (pour un changement d'entité du produit) entité(s) du produit de la requête

- ajout de la permission appkfet|produit_super_manager qui permet de gérer les produits de n'importe quelle entité
accord la permission pour toutes les entités, et équivaut à avoir les permission d'ajout, de modification et de suppression

- ajout de ProduitPermission pour employer ces nouvelles permissions. la vérification de entities_manageable se fait ici si possible (entité source du produit pour la modification de produit, entité du produit pour la suppression). L'entité de destination (création ou modification de l'entité du produit) est faite dans le serializer

_- modification de ProduitSerializer:_
- modification du champ nom_entite pour entite_id
- modification de create() pour vérifier que l'utilisateur peut créer un produit dans l'entité de la requête
- surcharge de update() pour vérifier que l'utilisateur peut modifier les produits de l'entité actuelle du produit, et qu'il peut modifier les produits de l'entité de destination (si il y a changement d'entité du produit)

- ajout de ProduitByEntityViewSet sous l'url api/produitsDansEntite/{cible_entity}
permet de récupérer tout les produits qui appartiennent à l'entité d'id <cible_entity>

- modification de la page admin des produits pour n'autoriser que les utilisateurs avec la permission produit_super_manager à modifier les produits depuis cette interface (j'ai pas trouvé comment faire la verification de l'entite comme avec le serializer pour l'api)

- ajout de l'attribut entities_manageable à la classe utilisateur pour lister toutes les entities_manageable des groupes auquel il appartient
- ajout des entities_manageable dans les attributs renvoyé par PermissionsSerializer (api/permission)

2024-05-09 08:53 UTC, peufgeul commented
C'est encore moi héhé
J'ai merge les modifications de main, rien de nouveau par rapport au premier commentaire

2024-06-20 14:04 UTC, peufgeul commented on api/serializers.py
> +            produit.bucquage()
je suis vraiment pas sûr si c'est le meilleur endroit pour appeler la méthode pour décrémenter le stock, mais c'est le dernier endroit où l'on a encore l'id du produit (et ici, on a même directement l'objet mais c'est pas nécessaire)

2024-06-29 18:44 UTC, Teiwin commented on api/serializers.py
> +            produit.bucquage()
on peut pas le faire dans la méthode save de bucquage, là ou on débite le consommateur et ou on écrit la ligne dans l'historique ?

2024-06-29 18:49 UTC, Teiwin commented on api/views.py
> +    def get_queryset(self):
il manque `*args` et `**kwargs` non ?

2024-06-29 19:03 UTC, peufgeul commented on api/serializers.py
> +            produit.bucquage()
le problème c'est que dans la méthode save de l'objet bucquage on a plus l'id du produit. on pourrait le retrouver mais dans ce cas il faut qu'on définisse le nom des produits comme unique

2024-06-29 19:09 UTC, Teiwin requested changes
quelques point qui me metten le doute, mais ça semble bien

2024-06-29 19:09 UTC, Teiwin commented on appuser/models.py
> +
je suis toujours pas persuadé de l'import comme ça.... il doit y avoir un moyen non?
@lenwe171175, @tag166tt ?

2024-06-29 19:15 UTC, peufgeul commented on api/views.py
> +    def get_queryset(self):
alors dans les autres get_queryset qui ont été crée il y en a où il y a effectivement ça.
mais dans le code source de Django Rest Framework j'ai l'impression que c'est pas mis [https://github.com/django/django/blob/a5215f9a3e9b8422678289c259e826f97e4dc63a/django/db/models/manager.py#L150](https://github.com/django/django/blob/a5215f9a3e9b8422678289c259e826f97e4dc63a/django/db/models/manager.py#L150)
et les rares exemples de la doc où il redéfinisse une méthode get_queryset y'a pas non plus. les kwargs ont l'air d'être accessible par self.kwargs

2024-06-29 19:20 UTC, Teiwin commented on api/serializers.py
> +            produit.bucquage()
pour moi le serializer ,c'est juste un moyen de parse toutes les données et de les serialiser ou déserialiser.
il n'y a pas vraiment de "processing" (sauf celui pour cast les données etc...)

peut être plutot dans le viewset ?

2024-06-29 19:22 UTC, Teiwin commented on api/views.py
> +    def get_queryset(self):
effectivement, je suis d'accord avec toi

2024-06-29 19:22 UTC, peufgeul commented on appkfet/models.py
> +    suivi_stock = models.BooleanField(default=False, verbose_name="Suivit du stock")
il me semble que j'ai pas mis de check lors du debucquage si le stock est à 0 ou non.
même si on aurait donc des produits qui irait en stock négatif, ça permettrait de voir quand des produits sont débucqués alors qu'ils sont pas sensé être en stock, et de pas avoir des produits dont on suivait initialement le stock qui deviennent considéré comme non suivi

et ça se retrouve au niveau interface utilisateur. Dans l'édition des produits, il y a une case pour activer ou non le suivit du stock, et si on suit le stock on rentre la valeur.
enfin, pour moi ça permettrait de mieux trouver des potentiels bug autour du stock si il en a.

2024-06-29 19:23 UTC, Teiwin commented on appkfet/models.py
> +    suivi_stock = models.BooleanField(default=False, verbose_name="Suivit du stock")
okay

2024-06-29 19:38 UTC, peufgeul commented on api/views.py
> +    def get_queryset(self):
c'est plutôt là le bon code source [https://github.com/encode/django-rest-framework/blob/e9f3fd250aa4176b43753097add1ddcd73ea9d55/rest_framework/generics.py#L52](url) mais j'avais la bonne conclusion

2024-06-29 20:02 UTC, peufgeul commented on api/serializers.py
> +            produit.bucquage()
je suis retourné voir la doc, et j'ai l'impression que c'est dans le serializer qu'on met les fonctions pour interagit avec les données de la bdd
[exemple](https://stackoverflow.com/questions/45100515/what-is-the-different-between-save-create-and-update-in-django-rest-fram)
[doc](https://www.django-rest-framework.org/api-guide/serializers/#overriding-save-directly)
mais peut-être que c'est pas ce qu'il faut faire dans notre cas précis

2024-07-03 22:42 UTC, OSiG43 commented on appuser/models.py
> +
Ya  `AppConfig.get_model(model_name, require_ready=True)`
https://docs.djangoproject.com/en/5.0/ref/applications/

même si généralement les imports circulaire ça sent un peu la mauvaise structure de code

2024-07-07 20:03 UTC, Teiwin approved these changes
lgtm

2024-07-07 20:03 UTC, merged